/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import static Secure.ChangePassword.user;
import java.awt.HeadlessException;
import java.sql.Statement; 
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class TransferWindow extends javax.swing.JFrame {

    private static final String[] SQL_STMT = {
		//0 Transfer
		"select current_balance from finance.User_Accounts as A Where Exists " +
			"(select Account_Number from finance.UserToAccount as UA where " +
			"A.Account_Number = UA.Account_Number and UA.Account_Number = %d " +
			"and UA.User_SSN = \"%s\")",
		//1 Transfer
		"select current_balance from finance.User_Accounts where Account_Number = %d",
		//2 Transfer
		"update finance.User_Accounts set current_balance = %f " +
			"where Account_Number = %d",
		//3 Transfer
		"insert into finance.Transaction (Point_of_sale, Amount, date) " +
			"values (\"online\", %f, now())",
		//4 Transfer
		"insert into finance.AcctToTrans " +
			"(Account_Number, Transaction_ID, Type, State) " +
			"values (%d, last_insert_id(), \"%s\", 0)",
	};

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public static User user = null;
    
    /**
     * Creates new form TransactionWindow
     */
    public TransferWindow(User u) {
        TransferWindow.user = u;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fromtxt = new javax.swing.JTextField();
        amnttxt = new javax.swing.JTextField();
        totxt = new javax.swing.JTextField();
        transferbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FROM Account Number:");

        jLabel2.setText("Transfer Window");

        jLabel3.setText("TO Account Number:");

        jLabel4.setText("Amount to Transfer:");

        fromtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromtxtActionPerformed(evt);
            }
        });

        amnttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amnttxtActionPerformed(evt);
            }
        });

        totxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totxtActionPerformed(evt);
            }
        });

        transferbtn.setText("Transfer");
        transferbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amnttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fromtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(transferbtn)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fromtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amnttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(transferbtn)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromtxtActionPerformed

    private void amnttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amnttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amnttxtActionPerformed

    private void totxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totxtActionPerformed

    private void transferbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferbtnActionPerformed
        // TODO add your handling code here:
        conn = MySqlConnect.ConnectDB();
        try {
            conn.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(TransferWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Double fromBalance = 0.0;
        Double toBalance = 0.0;

        Integer fromAct = Integer.parseInt(fromtxt.getText());
        Integer toAct = Integer.parseInt(totxt.getText());
        Double amt = Double.parseDouble(amnttxt.getText());
        
        String Sql = "";
        Statement smt = null;
        
        try {
            Sql = String.format(SQL_STMT[0], fromAct, user.getSSN());
            smt = conn.createStatement();
            ResultSet db = smt.executeQuery(Sql); 
        
            if(db.next()) {
                fromBalance = db.getDouble("current_balance");
                Sql = String.format(SQL_STMT[1], toAct); 
                db = smt.executeQuery(Sql);

                    if(db.next()) {
                        toBalance = db.getDouble("current_balance");
                        fromBalance -= amt; 
                        toBalance += amt; 

                        if(fromBalance < 0.0) {
                           JOptionPane.showMessageDialog(null, "Insufficient funds for transfer", "Try Again", JOptionPane.ERROR_MESSAGE);
                        } else {
                            // Update from balance
                            Sql = String.format(SQL_STMT[2], fromBalance, fromAct); 
                            smt.executeUpdate(Sql);

                            // Update to balance
                            Sql = String.format(SQL_STMT[2], toBalance, toAct); 
                            smt.executeUpdate(Sql); 

                            // Insert new transaction 
                            Sql = String.format(SQL_STMT[3], amt); 
                            smt.executeUpdate(Sql); 

                            // Insert association between transaction and from account 
                            Sql = String.format(SQL_STMT[4], fromAct, "debit"); 
                            smt.executeUpdate(Sql); 

                            // Insert association between transaction and to account
                            Sql = String.format(SQL_STMT[4], toAct, "credit"); 
                            smt.executeUpdate(Sql); 
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No account number associated with user", "Try Again", JOptionPane.ERROR_MESSAGE);               
                    }
            } else {
                JOptionPane.showMessageDialog(null, "No account number to transfer to", "Try Again", JOptionPane.ERROR_MESSAGE);               
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                // Wrap up procedure
                conn.commit();
                conn.setAutoCommit(true);
                conn.close();
                JOptionPane.showMessageDialog(null, "Transfer successful!");
                this.setVisible(false);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(TransferWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }                                    
    }//GEN-LAST:event_transferbtnActionPerformed

    /**
     * @param u
     */
    public static void runTransfer(User u)
    {
        JFrame frame = new TransferWindow(u);
        frame.pack();
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amnttxt;
    private javax.swing.JTextField fromtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField totxt;
    private javax.swing.JButton transferbtn;
    // End of variables declaration//GEN-END:variables
}
